apiVersion: apps/v1
kind: Deployment
metadata:
  name: ep04-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ep04-frontend
  template:
    metadata:
      labels:
        app: ep04-frontend
    spec:
      containers:
      - name: ep04-frontend
        image: drkn1/scd-ass3:ep04-frontend
        ports:
        - containerPort: 80